In [40]:
pip install bertopic

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Requirement already satisfied: bertopic in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (0.17.4)
Requirement already satisfied: hdbscan>=0.8.29 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from bertopic) (0.8.41)
Requirement already satisfied: umap-learn>=0.5.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from bertopic) (0.5.11)
Requirement already satisfied: numpy>=1.20.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from bertopic) (2.1.2)
Requirement already satisfied: pandas>=1.1.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from bertopic) (2.2.3)
Requirement already satisfied: plotly>=4.7.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from bertopic) (6.5.2)
Requirement already satisfied: scikit-learn>=1.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from bertopic) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from bertopic) (4.1.0)
Requirement already satisfied: tqdm>=4.41.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from bertopic) (4.67.1)
Requirement already satisfied: llvmlite>0.36.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from bertopic) (0.46.0)
Requirement already satisfied: scipy>=1.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from hdbscan>=0.8.29->bertopic) (1.15.3)
Requirement already satisfied: joblib>=1.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from hdbscan>=0.8.29->bertopic) (1.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: narwhals>=1.15.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from plotly>=4.7.0->bertopic) (1.41.1)
Requirement already satisfied: packaging in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from plotly>=4.7.0->bertopic) (24.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from sentence-transformers>=0.4.1->bertopic) (4.52.4)
Requirement already satisfied: torch>=1.11.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from sentence-transformers>=0.4.1->bertopic) (2.7.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from sentence-transformers>=0.4.1->bertopic) (0.33.0)
Requirement already satisfied: Pillow in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from sentence-transformers>=0.4.1->bertopic) (11.2.1)
Requirement already satisfied: typing_extensions>=4.5.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from sentence-transformers>=0.4.1->bertopic) (4.13.2)
Requirement already satisfied: numba>=0.51.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from umap-learn>=0.5.0->bertopic) (0.64.0)
Requirement already satisfied: pynndescent>=0.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from umap-learn>=0.5.0->bertopic) (0.6.0)
Requirement already satisfied: filelock in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2025.5.1)
Requirement already satisfied: pyyaml>=5.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (6.0.2)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2.32.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (1.1.3)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (80.3.1)
Requirement already satisfied: sympy>=1.13.3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.14.0)
Requirement already satisfied: networkx in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.5)
Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.5.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2025.4.26)

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [41]:
pip install vaderSentiment

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Requirement already satisfied: vaderSentiment in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (3.3.2)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from vaderSentiment) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->vaderSentiment) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->vaderSentiment) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->vaderSentiment) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->vaderSentiment) (2025.4.26)

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [42]:
import pandas as pd
import numpy as np
import torch
from transformers import AutoTokenizer, AutoModel
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from bertopic import BERTopic
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import re
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [43]:
ai_df = pd.read_csv('AI.csv', encoding='latin1')
ai_df.rename(columns={'Number': 'id'}, inplace=True)
benefits_df = pd.read_csv('dat_benefits_text.csv', encoding='latin1')
risks_df = pd.read_csv('dat_risks_text.csv', encoding='latin1')

In [44]:
ai_df.head()

,id,risks_AI_avg,support_company,gender_bin,objective_threat,trait_risk,educ_short,percent_job_gain,age_group,education,country,manipulation_check2,weight
0,1,4.0,4.0,Men,NaN,certain,0,100%,45 to 64,HS or less,US,Pass,0.2703
1,2,4.0,2.0,NaN,0.200000,certain,1,30%,45 to 64,Postgrad,US,Pass,0.2709
2,3,3.0,4.0,Men,NaN,certain,0,70%,45 to 64,HS or less,US,Pass,0.6464
3,4,2.5,3.0,Men,0.466667,certain,0,100%,30 to 44,HS or less,US,Pass,2.7281
4,5,3.0,4.0,Men,NaN,certain,0,30%,65 or older,Some college,US,Fail,0.8643

In [45]:
benefits_df.head()

   id benefits_text gender_bin gender_cat
0   1      Not sure        Man        Man
1   2   No I cannot        Man        Man
2   3       No idea      Woman      Woman
3   4     Efficency        Man        Man
4   5   In medicine      Woman      Woman

In [46]:
risks_df.head()

   id             risks_text gender_bin gender_cat
0   2               Not sure        Man        Man
1   3  Taking over the world        Man        Man
2   8     People losing jobs      Woman      Woman
3  10               Job loss        Man        Man
4  12                  Crime      Woman      Woman

In [47]:
df = ai_df.merge(benefits_df, on="id", how="left")
df = df.merge(risks_df, on="id", how="left")

In [48]:
df.head()

,id,risks_AI_avg,support_company,gender_bin_x,objective_threat,trait_risk,educ_short,percent_job_gain,age_group,education,country,manipulation_check2,weight,benefits_text,gender_bin_y,gender_cat_x,risks_text,gender_bin,gender_cat_y
0,1,4.0,4.0,Men,NaN,certain,0,100%,45 to 64,HS or less,US,Pass,0.2703,Not sure,Man,Man,NaN,NaN,NaN
1,2,4.0,2.0,NaN,0.200000,certain,1,30%,45 to 64,Postgrad,US,Pass,0.2709,No I cannot,Man,Man,Not sure,Man,Man
2,3,3.0,4.0,Men,NaN,certain,0,70%,45 to 64,HS or less,US,Pass,0.6464,No idea,Woman,Woman,Taking over the world,Man,Man
3,4,2.5,3.0,Men,0.466667,certain,0,100%,30 to 44,HS or less,US,Pass,2.7281,Efficency,Man,Man,NaN,NaN,NaN
4,5,3.0,4.0,Men,NaN,certain,0,30%,65 or older,Some college,US,Fail,0.8643,In medicine,Woman,Woman,NaN,NaN,NaN

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3049 entries, 0 to 3048
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   3049 non-null   int64
 1   risks_AI_avg         3049 non-null   float64
 2   support_company      2689 non-null   float64
 3   gender_bin_x         3007 non-null   object
 4   objective_threat     1600 non-null   float64
 5   trait_risk           3049 non-null   object
 6   educ_short           3049 non-null   int64
 7   percent_job_gain     3049 non-null   object
 8   age_group            3049 non-null   object
 9   education            3049 non-null   object
 10  country              3049 non-null   object
 11  manipulation_check2  3045 non-null   object
 12  weight               3049 non-null   float64
 13  benefits_text        2891 non-null   object
 14  gender_bin_y         3001 non-null   object
 15  gender_cat_x         3001 non-null   object
 16  risks_text           1481 non-null   object
 17  gender_bin           1497 non-null   object
 18  gender_cat_y         1497 non-null   object
dtypes: float64(4), int64(2), object(13)
memory usage: 452.7+ KB

In [50]:
df.describe()

,id,risks_AI_avg,support_company,objective_threat,educ_short,weight
count,3049.000000,3049.000000,2689.000000,1600.000000,3049.000000,3049.000000
mean,1525.000000,4.653657,3.119747,0.518458,0.299442,0.999236
std,880.314811,2.508140,1.094399,0.218976,0.458089,0.616210
min,1.000000,0.000000,1.000000,0.000000,0.000000,0.137600
25%,763.000000,3.000000,2.000000,0.366667,0.000000,0.647400
50%,1525.000000,5.000000,3.000000,0.500000,0.000000,0.834400
75%,2287.000000,6.000000,4.000000,0.666667,1.000000,1.135600
max,3049.000000,10.000000,5.000000,1.000000,1.000000,5.739000

In [51]:
df["combined_text"] = df[[c for c in df.columns if c.endswith("text")]].fillna("").agg(" ".join, axis=1)

In [52]:
df.head()

,id,risks_AI_avg,support_company,gender_bin_x,objective_threat,trait_risk,educ_short,percent_job_gain,age_group,education,country,manipulation_check2,weight,benefits_text,gender_bin_y,gender_cat_x,risks_text,gender_bin,gender_cat_y,combined_text
0,1,4.0,4.0,Men,NaN,certain,0,100%,45 to 64,HS or less,US,Pass,0.2703,Not sure,Man,Man,NaN,NaN,NaN,Not sure
1,2,4.0,2.0,NaN,0.200000,certain,1,30%,45 to 64,Postgrad,US,Pass,0.2709,No I cannot,Man,Man,Not sure,Man,Man,No I cannot Not sure
2,3,3.0,4.0,Men,NaN,certain,0,70%,45 to 64,HS or less,US,Pass,0.6464,No idea,Woman,Woman,Taking over the world,Man,Man,No idea Taking over the world
3,4,2.5,3.0,Men,0.466667,certain,0,100%,30 to 44,HS or less,US,Pass,2.7281,Efficency,Man,Man,NaN,NaN,NaN,Efficency
4,5,3.0,4.0,Men,NaN,certain,0,30%,65 or older,Some college,US,Fail,0.8643,In medicine,Woman,Woman,NaN,NaN,NaN,In medicine

# 3. RoBERTa Embeddings (HuggingFace + PyTorch)

In [53]:
tokenizer = AutoTokenizer.from_pretrained("roberta-base")
model = AutoModel.from_pretrained("roberta-base")
model.eval()

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

RobertaModel(
  (embeddings): RobertaEmbeddings(
    (word_embeddings): Embedding(50265, 768, padding_idx=1)
    (position_embeddings): Embedding(514, 768, padding_idx=1)
    (token_type_embeddings): Embedding(1, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): RobertaEncoder(
    (layer): ModuleList(
      (0-11): 12 x RobertaLayer(
        (attention): RobertaAttention(
          (self): RobertaSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): RobertaSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): RobertaIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
          (intermediate_act_fn): GELUActivation()
        )
        (output): RobertaOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
  )
  (pooler): RobertaPooler(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (activation): Tanh()
  )
)

In [54]:
@torch.no_grad()
def get_embeddings(text_list, batch_size=16, max_length=128):
    all_emb = []
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i+batch_size]
        inputs = tokenizer(batch, padding=True, truncation=True, return_tensors="pt", max_length=max_length)
        outputs = model(**inputs)
        # mean pooling
        emb = outputs.last_hidden_state.mean(dim=1).cpu().numpy()
        all_emb.append(emb)
    return np.vstack(all_emb)

print("Generating embeddings...")
embeddings = get_embeddings(df["combined_text"].tolist())

Generating embeddings...

# 4. BERTopic (Topic Proportions as Features)

In [55]:
topic_model = BERTopic(
    verbose=True,
    calculate_probabilities=True
)

topics, probs = topic_model.fit_transform(df["combined_text"], embeddings)

df["topic"] = topics
# df["is_outlier"] = (df["topic"] == -1).astype(int)

# Now this works
probs = np.array(probs)

probs_df = pd.DataFrame(
    probs,
    columns=[f"topic_{i}" for i in range(probs.shape[1])]
)

# probs_df = probs_df.div(probs_df.sum(axis=1).replace(0, 1), axis=0)

df = pd.concat([df.reset_index(drop=True), probs_df], axis=1)

# Inspect topics
print(topic_model.get_topic_info().head(10))
for tid in topic_model.get_topic_info()["Topic"].head(8):
    print(f"\nTopic {tid}:")
    print(topic_model.get_topic(tid))

2026-03-18 16:45:50,574 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-03-18 16:45:57,560 - BERTopic - Dimensionality - Completed ✓
2026-03-18 16:45:57,561 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-03-18 16:45:57,821 - BERTopic - Cluster - Completed ✓
2026-03-18 16:45:57,829 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-03-18 16:45:57,868 - BERTopic - Representation - Completed ✓

   Topic  Count                                   Name  \
0     -1    339                   -1_there_the_none_no
1      0   1397                        0_and_the_of_ai
2      1    238                    1_to_do_able_enough
3      2    135                     2_dont_know_im_any
4      3     64  3_speed_medical_healthcare_convenient
5      4     60               4_ease_saves_work_faster
6      5     57       5_efficiency_cost_operation_less
7      6     48    6_productivity_makes_improving_life
8      7     47                    7_idea_have_no_know
9      8     41     8_easier_making_things_efficiently

                                      Representation  \
0  [there, the, none, no, faster, for, are, is, a...
1     [and, the, of, ai, it, to, in, for, can, jobs]
2  [to, do, able, enough, people, being, make, it...
3  [dont, know, im, any, about, not, there, takin...
4  [speed, medical, healthcare, convenient, produ...
5  [ease, saves, work, faster, knowledge, respons...
6  [efficiency, cost, operation, less, savings, q...
7  [productivity, makes, improving, life, easier,...
8  [idea, have, no, know, dont, am, im, about, su...
9  [easier, making, things, efficiently, life, un...

                                 Representative_Docs
0  [THE BIGGEST BENEFIT FROM AUTOMATION AND ARTIF...
1  [There are many potential benefits of automati...
2  [Less work for people to do , That people will...
3    [Donât know , I donât know , Donât know ]
4                           [speed , Speed , Speed ]
5          [Saves time , saves time , Ease of work ]
6  [speed and efficiency , Efficiency, cost savin...
7  [Makes life easier , Makes life easier , Incre...
8  [I have no idea , I have no idea , I have no i...
9  [Making life easier , Making certain things in...

Topic -1:
[('there', np.float64(0.0215416799236912)), ('the', np.float64(0.021112740560737253)), ('none', np.float64(0.02049958515962362)), ('no', np.float64(0.019144292489833202)), ('faster', np.float64(0.018309963999528507)), ('for', np.float64(0.017325511146002448)), ('are', np.float64(0.016659521751147228)), ('is', np.float64(0.01650854255970232)), ('and', np.float64(0.01639282574557781)), ('of', np.float64(0.016132863056461902))]

Topic 0:
[('and', np.float64(0.019983432621157277)), ('the', np.float64(0.019246848322886156)), ('of', np.float64(0.01898784488127505)), ('ai', np.float64(0.015557340496342763)), ('it', np.float64(0.015156635422832805)), ('to', np.float64(0.014837024673279567)), ('in', np.float64(0.014662117055455382)), ('for', np.float64(0.014577269387062407)), ('can', np.float64(0.014461846869474057)), ('jobs', np.float64(0.014400505222067057))]

Topic 1:
[('to', np.float64(0.06279926987813457)), ('do', np.float64(0.029138709886017522)), ('able', np.float64(0.025529756328243974)), ('enough', np.float64(0.024124766308178815)), ('people', np.float64(0.021209759648978452)), ('being', np.float64(0.020217712271314584)), ('make', np.float64(0.018493119166191403)), ('it', np.float64(0.01525610282742304)), ('and', np.float64(0.015228899996641055)), ('they', np.float64(0.014487805300398582))]

Topic 2:
[('dont', np.float64(0.12474101290272391)), ('know', np.float64(0.10890418137670373)), ('im', np.float64(0.0378125897780403)), ('any', np.float64(0.03109978802697278)), ('about', np.float64(0.029947740970904184)), ('not', np.float64(0.028293485499102763)), ('there', np.float64(0.02736533269317972)), ('taking', np.float64(0.027349969712495956)), ('sure', np.float64(0.02549068089588562)), ('think', np.float64(0.02516621053207139))]

Topic 3:
[('speed', np.float64(0.14292424997155845)), ('medical', np.float64(0.11057500513932907)), ('healthcare', np.float64(0.08201609874779728)), ('convenient', np.float64(0.0649820427414199)), ('products', np.float64(0.06062469916550726)), ('solving', np.float64(0.05660390260554723)), ('medicine', np.float64(0.04838999012471894)), ('humans', np.float64(0.04813066447146126)), ('specified', np.float64(0.045767867105820606)), ('deliveries', np.float64(0.045767867105820606))]

Topic 4:
[('ease', np.float64(0.09532040888361745)), ('saves', np.float64(0.08732161425469948)), ('work', np.float64(0.0817507377111875)), ('faster', np.float64(0.0784598018751726)), ('knowledge', np.float64(0.07788288724286306)), ('responses', np.float64(0.07317897625459839)), ('time', np.float64(0.07243333576679302)), ('money', np.float64(0.07170339041123207)), ('productivity', np.float64(0.0593016412605231)), ('quicker', np.float64(0.05758099437759313))]

Topic 5:
[('efficiency', np.float64(0.1185555847739039)), ('cost', np.float64(0.07860215803399745)), ('operation', np.float64(0.06655793072451477)), ('less', np.float64(0.06548063717034243)), ('savings', np.float64(0.06354693925574496)), ('quality', np.float64(0.058874487985074705)), ('and', np.float64(0.05542805543081255)), ('saving', np.float64(0.05192192482857537)), ('speed', np.float64(0.051523309866290216)), ('time', np.float64(0.048288890511195344))]

Topic 6:
[('productivity', np.float64(0.06900554619406324)), ('makes', np.float64(0.05578647598719468)), ('improving', np.float64(0.05545914698683197)), ('life', np.float64(0.05013993994631872)), ('easier', np.float64(0.03456437926598396)), ('high', np.float64(0.03353745989628165)), ('improves', np.float64(0.03353745989628165)), ('efficiency', np.float64(0.03104000764989484)), ('performance', np.float64(0.030051526474217802)), ('reduces', np.float64(0.029521532541819304))]

# 5. Sentiment (VADER)

In [56]:
analyzer = SentimentIntensityAnalyzer()

def get_sentiment(text):
    if not isinstance(text, str) or text.strip() == "":
        return 0.0
    return analyzer.polarity_scores(text)["compound"]  # -1 to 1

print("Computing sentiment...")
df["sentiment"] = df["combined_text"].apply(get_sentiment)

Computing sentiment...

In [57]:
df.head()

,id,risks_AI_avg,support_company,gender_bin_x,objective_threat,trait_risk,educ_short,percent_job_gain,age_group,education,...,topic_31,topic_32,topic_33,topic_34,topic_35,topic_36,topic_37,topic_38,topic_39,sentiment
0,1,4.0,4.0,Men,NaN,certain,0,100%,45 to 64,HS or less,...,4.772585e-308,7.659696e-309,4.579036e-308,5.163023e-308,2.784349e-308,1.106384e-308,7.543628e-308,8.522082e-309,7.358054e-308,-0.2411
1,2,4.0,2.0,NaN,0.200000,certain,1,30%,45 to 64,Postgrad,...,2.434875e-02,3.379408e-03,2.168407e-02,4.267169e-02,1.855492e-02,5.289022e-03,1.640313e-02,4.050463e-03,2.685738e-02,-0.1250
2,3,3.0,4.0,Men,NaN,certain,0,70%,45 to 64,HS or less,...,2.514947e-02,3.658890e-03,2.281925e-02,4.353050e-02,2.080159e-02,5.788283e-03,1.646974e-02,4.304862e-03,2.692077e-02,-0.2960
3,4,2.5,3.0,Men,0.466667,certain,0,100%,30 to 44,HS or less,...,1.254601e-02,1.545812e-03,1.442863e-02,1.159352e-02,6.944757e-02,2.420494e-03,6.152697e-03,1.694968e-03,1.048419e-02,0.0000
4,5,3.0,4.0,Men,NaN,certain,0,30%,65 or older,Some college,...,4.595418e-308,6.767595e-309,5.217087e-308,4.478315e-308,1.746591e-307,1.052367e-308,2.474884e-308,7.401013e-309,3.957668e-308,0.0000

# 6. Uncertainty Score (0-5)
## Simple lexicon-based scoring

In [58]:
uncertain_terms = [
    r"\bmaybe\b", r"\bnot sure\b", r"\bunsure\b", r"\buncertain\b", r"\bi think\b",
    r"\bprobably\b", r"\bpossibly\b", r"\bcould\b", r"\bmight\b", r"\bperhaps\b",
    r"\bdon'?t know\b", r"\bno idea\b"
]
uncertain_regex = re.compile("|".join(uncertain_terms), flags=re.IGNORECASE)

def uncertainty_score(text, cap=5):
    if not isinstance(text, str) or text.strip() == "":
        return 0
    matches = re.findall(uncertain_regex, text)
    return int(min(len(matches), cap))

print("Computing uncertainty...")
df["uncertainty"] = df["combined_text"].apply(uncertainty_score)

Computing uncertainty...

In [59]:
df.head()

,id,risks_AI_avg,support_company,gender_bin_x,objective_threat,trait_risk,educ_short,percent_job_gain,age_group,education,...,topic_32,topic_33,topic_34,topic_35,topic_36,topic_37,topic_38,topic_39,sentiment,uncertainty
0,1,4.0,4.0,Men,NaN,certain,0,100%,45 to 64,HS or less,...,7.659696e-309,4.579036e-308,5.163023e-308,2.784349e-308,1.106384e-308,7.543628e-308,8.522082e-309,7.358054e-308,-0.2411,1
1,2,4.0,2.0,NaN,0.200000,certain,1,30%,45 to 64,Postgrad,...,3.379408e-03,2.168407e-02,4.267169e-02,1.855492e-02,5.289022e-03,1.640313e-02,4.050463e-03,2.685738e-02,-0.1250,1
2,3,3.0,4.0,Men,NaN,certain,0,70%,45 to 64,HS or less,...,3.658890e-03,2.281925e-02,4.353050e-02,2.080159e-02,5.788283e-03,1.646974e-02,4.304862e-03,2.692077e-02,-0.2960,1
3,4,2.5,3.0,Men,0.466667,certain,0,100%,30 to 44,HS or less,...,1.545812e-03,1.442863e-02,1.159352e-02,6.944757e-02,2.420494e-03,6.152697e-03,1.694968e-03,1.048419e-02,0.0000,0
4,5,3.0,4.0,Men,NaN,certain,0,30%,65 or older,Some college,...,6.767595e-309,5.217087e-308,4.478315e-308,1.746591e-307,1.052367e-308,2.474884e-308,7.401013e-309,3.957668e-308,0.0000,0

In [60]:
print(df.columns.tolist())

['id', 'risks_AI_avg', 'support_company', 'gender_bin_x', 'objective_threat', 'trait_risk', 'educ_short', 'percent_job_gain', 'age_group', 'education', 'country', 'manipulation_check2', 'weight', 'benefits_text', 'gender_bin_y', 'gender_cat_x', 'risks_text', 'gender_bin', 'gender_cat_y', 'combined_text', 'topic', 'topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5', 'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10', 'topic_11', 'topic_12', 'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17', 'topic_18', 'topic_19', 'topic_20', 'topic_21', 'topic_22', 'topic_23', 'topic_24', 'topic_25', 'topic_26', 'topic_27', 'topic_28', 'topic_29', 'topic_30', 'topic_31', 'topic_32', 'topic_33', 'topic_34', 'topic_35', 'topic_36', 'topic_37', 'topic_38', 'topic_39', 'sentiment', 'uncertainty']

In [61]:
df = df.loc[:, ~df.columns.duplicated()]

In [63]:
df["gender_clean"] = df["gender_bin"]

# Fill missing from other sources
df["gender_clean"] = df["gender_clean"].fillna(df["gender_bin_x"])
df["gender_clean"] = df["gender_clean"].fillna(df["gender_bin_y"])

In [64]:
df["gender_clean"].isna().sum()

np.int64(0)

# 7. Build Feature Set

In [65]:
#structured = [c for c in [
#    "gender", "age", "education", "risk_orientation"
#] if c in df.columns]

structured = [
    "gender_clean",
    "age_group",
    "education",
    "trait_risk",
    "objective_threat",
    "percent_job_gain"
]

topic_cols = [c for c in df.columns if c.startswith("topic_")]
text_feats = topic_cols + ["sentiment", "uncertainty"]

# Targets
risk_target = "risks_AI_avg"            # continuous
support_target = "support_company"     # ordinal (1-5)

# Prepare modeling df
model_cols = structured + text_feats + [risk_target, support_target]
df_m = df[model_cols].dropna().copy()

# Basic encoding (example)
for col in structured:
    if df_m[col].dtype == "object":
        df_m[col] = df_m[col].astype("category").cat.codes

In [66]:
# 8. Model A: Text + Structured -> Risk Perception

In [67]:
X = df_m[structured + text_feats]
y = df_m[risk_target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf = RandomForestRegressor(n_estimators=300, random_state=42)
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)
print("\nRisk Model Performance")
print("MSE:", mean_squared_error(y_test, y_pred))
print("R2:", r2_score(y_test, y_pred))

# Feature importance
feat_imp = pd.DataFrame({"feature": X.columns, "importance": rf.feature_importances_})\
    .sort_values("importance", ascending=False)
print("\nTop Features (Risk):")
print(feat_imp.head(20))

Risk Model Performance
MSE: 6.531324151234568
R2: 0.04761384397726687

Top Features (Risk):
             feature  importance
4   objective_threat    0.100706
46         sentiment    0.073680
1          age_group    0.046707
6            topic_0    0.035502
5   percent_job_gain    0.031839
0       gender_clean    0.029532
2          education    0.027447
9            topic_3    0.024846
7            topic_1    0.024515
16          topic_10    0.023971
8            topic_2    0.023061
40          topic_34    0.021751
3         trait_risk    0.020867
20          topic_14    0.020472
36          topic_30    0.019819
31          topic_25    0.018509
19          topic_13    0.018158
15           topic_9    0.017327
14           topic_8    0.017308
41          topic_35    0.017100

In [68]:
# 9. Model B: Risk -> AI Support (Ordinal via OLS approx)
# (For proper ordinal, use statsmodels OrderedModel)

In [69]:
X2 = df_m[[risk_target] + structured + text_feats]
y2 = df_m[support_target]

X2 = sm.add_constant(X2)
ols_support = sm.OLS(y2, X2).fit(cov_type='HC3')
print("\nSupport Model (OLS approx):")
print(ols_support.summary())

Support Model (OLS approx):
                            OLS Regression Results
==============================================================================
Dep. Variable:        support_company   R-squared:                       0.140
Model:                            OLS   Adj. R-squared:                  0.110
Method:                 Least Squares   F-statistic:                     4.762
Date:                Wed, 18 Mar 2026   Prob (F-statistic):           2.14e-23
Time:                        16:53:07   Log-Likelihood:                -2041.3
No. Observations:                1436   AIC:                             4183.
Df Residuals:                    1386   BIC:                             4446.
Df Model:                          49
Covariance Type:                  HC3
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
const                4.0257      0.195     20.638      0.000       3.643       4.408
risks_AI_avg        -0.1217      0.013     -9.550      0.000      -0.147      -0.097
gender_clean        -0.0233      0.026     -0.887      0.375      -0.075       0.028
age_group           -0.0744      0.032     -2.315      0.021      -0.137      -0.011
education            0.0194      0.025      0.787      0.431      -0.029       0.068
trait_risk           0.1032      0.067      1.538      0.124      -0.028       0.235
objective_threat    -0.3500      0.139     -2.527      0.012      -0.621      -0.078
percent_job_gain    -0.0500      0.025     -2.027      0.043      -0.098      -0.002
topic_0              0.0645      0.156      0.413      0.679      -0.241       0.370
topic_1              0.1785      0.193      0.924      0.356      -0.200       0.557
topic_2             -0.2090      0.224     -0.931      0.352      -0.649       0.231
topic_3             -0.0155      0.339     -0.046      0.964      -0.681       0.650
topic_4              0.2080      0.352      0.590      0.555      -0.483       0.898
topic_5             -0.1254      0.487     -0.257      0.797      -1.081       0.830
topic_6             -0.2943      0.675     -0.436      0.663      -1.617       1.028
topic_7             -0.2279      0.286     -0.798      0.425      -0.788       0.332
topic_8             -0.1033      0.352     -0.293      0.769      -0.794       0.587
topic_9              0.0350      0.450      0.078      0.938      -0.848       0.918
topic_10            -0.4897      0.519     -0.943      0.346      -1.507       0.528
topic_11            -0.2997      0.491     -0.610      0.542      -1.263       0.663
topic_12            -0.3525      0.786     -0.449      0.654      -1.893       1.188
topic_13            -0.5521      0.565     -0.977      0.329      -1.660       0.556
topic_14             0.1346      0.555      0.242      0.809      -0.954       1.223
topic_15            -0.5849      0.322     -1.815      0.070      -1.217       0.047
topic_16             0.4611      0.598      0.772      0.440      -0.710       1.632
topic_17            -0.4374      0.371     -1.179      0.238      -1.165       0.290
topic_18            -0.0761      0.708     -0.108      0.914      -1.463       1.311
topic_19             0.6876      0.314      2.193      0.028       0.073       1.302
topic_20             0.3420      0.441      0.775      0.438      -0.523       1.207
topic_21             0.5292      0.316      1.675      0.094      -0.090       1.148
topic_22             0.5266      0.530      0.994      0.320      -0.512       1.565
topic_23             0.4364      0.412      1.059      0.290      -0.372       1.244
topic_24             0.7522      0.293      2.564      0.010       0.177       1.327
topic_25             0.2552      0.345      0.740      0.459      -0.421       0.931
topic_26             0.3946      0.436      0.904      0.366      -0.461       1.250
topic_27             0.3881      0.324      1.199      0.230      -0.246       1.022
topic_28             0.7970      0.442      1.801      0.072      -0.070       1.664
topic_29             0.5349      0.485      1.104      0.270      -0.415       1.485
topic_30            -0.2347      0.378     -0.620      0.535      -0.977       0.507
topic_31             0.3081      0.453      0.680      0.496      -0.580       1.196
topic_32             0.3360      0.482      0.698      0.485      -0.608       1.280
topic_33            -0.6132      0.553     -1.109      0.267      -1.697       0.470
topic_34            -0.2721      0.337     -0.807      0.420      -0.933       0.389
topic_35            -0.2283      0.499     -0.458      0.647      -1.206       0.749
topic_36            -0.3467      0.430     -0.807      0.420      -1.189       0.495
topic_37             0.5316      0.285      1.868      0.062      -0.026       1.089
topic_38             0.0490      1.775      0.028      0.978      -3.431       3.529
topic_39            -1.1199      0.793     -1.413      0.158      -2.674       0.434
sentiment           -0.0233      0.082     -0.283      0.777      -0.184       0.138
uncertainty         -0.0776      0.067     -1.160      0.246      -0.209       0.054
==============================================================================
Omnibus:                       34.253   Durbin-Watson:                   1.930
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               33.340
Skew:                          -0.338   Prob(JB):                     5.76e-08
Kurtosis:                       2.684   Cond. No.                         214.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [70]:
# 10. Mediation Analysis (Baron & Kenny style)
# Path: Text -> Risk -> Support

In [75]:
# Step 1: M ~ X (Risk on Text+Structured)
formula_m = f"{risk_target} ~ " + " + ".join(structured + text_feats)
model_m = smf.ols(formula_m, data=df_m).fit(cov_type='HC3')

# Step 2: Y ~ X (Support on Text+Structured)
formula_yx = f"{support_target} ~ " + " + ".join(structured + text_feats)
model_yx = smf.ols(formula_yx, data=df_m).fit(cov_type='HC3')

# Step 3: Y ~ M + X (Support on Risk + Text+Structured)
formula_y = f"{support_target} ~ {risk_target} + " + " + ".join(structured + text_feats)
model_y = smf.ols(formula_y, data=df_m).fit(cov_type='HC3')

print("\nMediation Results:")
print("\nModel M (Risk ~ X):\n", model_m.summary())
print("\nModel Y|X (Support ~ X):\n", model_yx.summary())
print("\nModel Y (Support ~ Risk + X):\n", model_y.summary())

Mediation Results:

Model M (Risk ~ X):
                             OLS Regression Results
==============================================================================
Dep. Variable:           risks_AI_avg   R-squared:                       0.118
Model:                            OLS   Adj. R-squared:                  0.088
Method:                 Least Squares   F-statistic:                     5.276
Date:                Wed, 18 Mar 2026   Prob (F-statistic):           1.04e-26
Time:                        16:54:26   Log-Likelihood:                -3306.2
No. Observations:                1436   AIC:                             6710.
Df Residuals:                    1387   BIC:                             6969.
Df Model:                          48
Covariance Type:                  HC3
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            2.7604      0.432      6.395      0.000       1.914       3.606
gender_clean         0.1717      0.062      2.780      0.005       0.051       0.293
age_group            0.4286      0.073      5.848      0.000       0.285       0.572
education            0.1291      0.059      2.206      0.027       0.014       0.244
trait_risk          -0.8132      0.157     -5.178      0.000      -1.121      -0.505
objective_threat     1.7996      0.335      5.367      0.000       1.142       2.457
percent_job_gain    -0.0698      0.059     -1.180      0.238      -0.186       0.046
topic_0              0.0497      0.356      0.139      0.889      -0.649       0.748
topic_1             -0.2303      0.433     -0.532      0.595      -1.078       0.618
topic_2             -0.4287      0.527     -0.813      0.416      -1.462       0.604
topic_3              0.9842      0.783      1.256      0.209      -0.551       2.520
topic_4              0.9821      0.659      1.490      0.136      -0.310       2.274
topic_5             -1.9340      1.007     -1.920      0.055      -3.908       0.040
topic_6             -0.4512      1.295     -0.348      0.728      -2.989       2.087
topic_7              0.1699      0.873      0.195      0.846      -1.540       1.880
topic_8              1.2031      0.827      1.455      0.146      -0.417       2.824
topic_9              0.8201      1.152      0.712      0.477      -1.438       3.079
topic_10            -2.3282      0.869     -2.678      0.007      -4.032      -0.624
topic_11             0.7982      1.345      0.593      0.553      -1.839       3.435
topic_12            -2.0164      1.547     -1.303      0.192      -5.049       1.016
topic_13             1.0161      1.067      0.952      0.341      -1.075       3.107
topic_14             0.7421      1.402      0.529      0.596      -2.005       3.489
topic_15            -0.3045      1.479     -0.206      0.837      -3.203       2.595
topic_16            -0.5317      1.031     -0.516      0.606      -2.552       1.489
topic_17             0.6698      0.932      0.719      0.472      -1.156       2.496
topic_18             0.1690      1.406      0.120      0.904      -2.586       2.924
topic_19            -0.0415      0.689     -0.060      0.952      -1.392       1.308
topic_20            -0.9727      0.740     -1.314      0.189      -2.424       0.479
topic_21            -0.7988      0.503     -1.588      0.112      -1.785       0.187
topic_22            -1.3050      1.197     -1.090      0.276      -3.651       1.041
topic_23             1.4533      0.783      1.855      0.064      -0.082       2.989
topic_24            -0.1431      0.734     -0.195      0.845      -1.582       1.296
topic_25             1.6843      1.017      1.655      0.098      -0.310       3.679
topic_26             0.3021      0.750      0.403      0.687      -1.167       1.771
topic_27            -0.6475      0.931     -0.695      0.487      -2.473       1.178
topic_28            -1.6892      1.062     -1.591      0.112      -3.771       0.392
topic_29             0.2390      1.123      0.213      0.831      -1.961       2.439
topic_30             1.2563      1.445      0.870      0.385      -1.576       4.088
topic_31             0.4481      1.488      0.301      0.763      -2.468       3.364
topic_32             1.2928      0.883      1.465      0.143      -0.437       3.023
topic_33             0.6658      0.842      0.790      0.429      -0.985       2.317
topic_34            -0.0941      1.167     -0.081      0.936      -2.382       2.194
topic_35            -2.6488      0.522     -5.072      0.000      -3.672      -1.625
topic_36            -1.2686      0.941     -1.349      0.177      -3.112       0.575
topic_37            -1.7796      0.739     -2.409      0.016      -3.228      -0.332
topic_38            -0.9176      3.552     -0.258      0.796      -7.879       6.044
topic_39            -2.6481      1.177     -2.249      0.025      -4.956      -0.340
sentiment           -0.1096      0.185     -0.591      0.554      -0.473       0.254
uncertainty         -0.0252      0.152     -0.166      0.868      -0.323       0.272
==============================================================================
Omnibus:                       17.057   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               17.535
Skew:                           0.269   Prob(JB):                     0.000156
Kurtosis:                       2.939   Cond. No.                         124.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

Model Y|X (Support ~ X):
                             OLS Regression Results
==============================================================================
Dep. Variable:        support_company   R-squared:                       0.066
Model:                            OLS   Adj. R-squared:                  0.034
Method:                 Least Squares   F-statistic:                     2.546
Date:                Wed, 18 Mar 2026   Prob (F-statistic):           5.76e-08
Time:                        16:54:26   Log-Likelihood:                -2100.6
No. Observations:                1436   AIC:                             4299.
Df Residuals:                    1387   BIC:                             4557.
Df Model:                          48
Covariance Type:                  HC3
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            3.6898      0.196     18.836      0.000       3.306       4.074
gender_clean        -0.0442      0.027     -1.634      0.102      -0.097       0.009
age_group           -0.1266      0.033     -3.838      0.000      -0.191      -0.062
education            0.0037      0.026      0.144      0.886      -0.047       0.054
trait_risk           0.2021      0.070      2.906      0.004       0.066       0.338
objective_threat    -0.5690      0.144     -3.952      0.000      -0.851      -0.287
percent_job_gain    -0.0415      0.026     -1.622      0.105      -0.092       0.009
topic_0              0.0585      0.160      0.366      0.714      -0.255       0.372
topic_1              0.2066      0.201      1.030      0.303      -0.186       0.600
topic_2             -0.1568      0.232     -0.675      0.500      -0.612       0.299
topic_3             -0.1352      0.382     -0.354      0.724      -0.885       0.614
topic_4              0.0885      0.347      0.255      0.799      -0.591       0.768
topic_5              0.1099      0.491      0.224      0.823      -0.852       1.072
topic_6             -0.2393      0.710     -0.337      0.736      -1.631       1.152
topic_7             -0.2486      0.298     -0.833      0.405      -0.833       0.336
topic_8             -0.2497      0.344     -0.726      0.468      -0.923       0.424
topic_9             -0.0648      0.518     -0.125      0.900      -1.080       0.950
topic_10            -0.2064      0.499     -0.414      0.679      -1.183       0.771
topic_11            -0.3969      0.528     -0.751      0.452      -1.432       0.638
topic_12            -0.1071      0.838     -0.128      0.898      -1.749       1.534
topic_13            -0.6757      0.519     -1.302      0.193      -1.693       0.341
topic_14             0.0443      0.548      0.081      0.936      -1.029       1.117
topic_15            -0.5478      0.344     -1.591      0.112      -1.223       0.127
topic_16             0.5258      0.620      0.848      0.396      -0.689       1.741
topic_17            -0.5189      0.359     -1.446      0.148      -1.222       0.184
topic_18            -0.0967      0.600     -0.161      0.872      -1.272       1.079
topic_19             0.6926      0.320      2.162      0.031       0.065       1.321
topic_20             0.4604      0.445      1.035      0.301      -0.411       1.332
topic_21             0.6264      0.304      2.059      0.040       0.030       1.223
topic_22             0.6854      0.454      1.511      0.131      -0.204       1.575
topic_23             0.2596      0.467      0.556      0.578      -0.655       1.174
topic_24             0.7696      0.341      2.256      0.024       0.101       1.438
topic_25             0.0503      0.275      0.183      0.855      -0.489       0.589
topic_26             0.3579      0.469      0.763      0.445      -0.561       1.277
topic_27             0.4669      0.381      1.225      0.221      -0.280       1.214
topic_28             1.0025      0.506      1.981      0.048       0.011       1.994
topic_29             0.5058      0.462      1.094      0.274      -0.401       1.412
topic_30            -0.3876      0.530     -0.731      0.465      -1.427       0.652
topic_31             0.2536      0.461      0.551      0.582      -0.649       1.156
topic_32             0.1787      0.428      0.418      0.676      -0.660       1.017
topic_33            -0.6942      0.599     -1.159      0.246      -1.868       0.480
topic_34            -0.2606      0.418     -0.623      0.533      -1.081       0.559
topic_35             0.0940      0.482      0.195      0.846      -0.852       1.040
topic_36            -0.1923      0.467     -0.412      0.680      -1.108       0.723
topic_37             0.7481      0.259      2.891      0.004       0.241       1.255
topic_38             0.1607      1.345      0.119      0.905      -2.476       2.798
topic_39            -0.7976      0.720     -1.107      0.268      -2.210       0.614
sentiment           -0.0099      0.085     -0.117      0.907      -0.176       0.156
uncertainty         -0.0746      0.067     -1.115      0.265      -0.206       0.057
==============================================================================
Omnibus:                       54.979   Durbin-Watson:                   1.932
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               40.919
Skew:                          -0.316   Prob(JB):                     1.30e-09
Kurtosis:                       2.466   Cond. No.                         124.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

Model Y (Support ~ Risk + X):
                             OLS Regression Results
==============================================================================
Dep. Variable:        support_company   R-squared:                       0.140
Model:                            OLS   Adj. R-squared:                  0.110
Method:                 Least Squares   F-statistic:                     4.762
Date:                Wed, 18 Mar 2026   Prob (F-statistic):           2.14e-23
Time:                        16:54:26   Log-Likelihood:                -2041.3
No. Observations:                1436   AIC:                             4183.
Df Residuals:                    1386   BIC:                             4446.
Df Model:                          49
Covariance Type:                  HC3
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            4.0257      0.195     20.638      0.000       3.643       4.408
risks_AI_avg        -0.1217      0.013     -9.550      0.000      -0.147      -0.097
gender_clean        -0.0233      0.026     -0.887      0.375      -0.075       0.028
age_group           -0.0744      0.032     -2.315      0.021      -0.137      -0.011
education            0.0194      0.025      0.787      0.431      -0.029       0.068
trait_risk           0.1032      0.067      1.538      0.124      -0.028       0.235
objective_threat    -0.3500      0.139     -2.527      0.012      -0.621      -0.078
percent_job_gain    -0.0500      0.025     -2.027      0.043      -0.098      -0.002
topic_0              0.0645      0.156      0.413      0.679      -0.241       0.370
topic_1              0.1785      0.193      0.924      0.356      -0.200       0.557
topic_2             -0.2090      0.224     -0.931      0.352      -0.649       0.231
topic_3             -0.0155      0.339     -0.046      0.964      -0.681       0.650
topic_4              0.2080      0.352      0.590      0.555      -0.483       0.898
topic_5             -0.1254      0.487     -0.257      0.797      -1.081       0.830
topic_6             -0.2943      0.675     -0.436      0.663      -1.617       1.028
topic_7             -0.2279      0.286     -0.798      0.425      -0.788       0.332
topic_8             -0.1033      0.352     -0.293      0.769      -0.794       0.587
topic_9              0.0350      0.450      0.078      0.938      -0.848       0.918
topic_10            -0.4897      0.519     -0.943      0.346      -1.507       0.528
topic_11            -0.2997      0.491     -0.610      0.542      -1.263       0.663
topic_12            -0.3525      0.786     -0.449      0.654      -1.893       1.188
topic_13            -0.5521      0.565     -0.977      0.329      -1.660       0.556
topic_14             0.1346      0.555      0.242      0.809      -0.954       1.223
topic_15            -0.5849      0.322     -1.815      0.070      -1.217       0.047
topic_16             0.4611      0.598      0.772      0.440      -0.710       1.632
topic_17            -0.4374      0.371     -1.179      0.238      -1.165       0.290
topic_18            -0.0761      0.708     -0.108      0.914      -1.463       1.311
topic_19             0.6876      0.314      2.193      0.028       0.073       1.302
topic_20             0.3420      0.441      0.775      0.438      -0.523       1.207
topic_21             0.5292      0.316      1.675      0.094      -0.090       1.148
topic_22             0.5266      0.530      0.994      0.320      -0.512       1.565
topic_23             0.4364      0.412      1.059      0.290      -0.372       1.244
topic_24             0.7522      0.293      2.564      0.010       0.177       1.327
topic_25             0.2552      0.345      0.740      0.459      -0.421       0.931
topic_26             0.3946      0.436      0.904      0.366      -0.461       1.250
topic_27             0.3881      0.324      1.199      0.230      -0.246       1.022
topic_28             0.7970      0.442      1.801      0.072      -0.070       1.664
topic_29             0.5349      0.485      1.104      0.270      -0.415       1.485
topic_30            -0.2347      0.378     -0.620      0.535      -0.977       0.507
topic_31             0.3081      0.453      0.680      0.496      -0.580       1.196
topic_32             0.3360      0.482      0.698      0.485      -0.608       1.280
topic_33            -0.6132      0.553     -1.109      0.267      -1.697       0.470
topic_34            -0.2721      0.337     -0.807      0.420      -0.933       0.389
topic_35            -0.2283      0.499     -0.458      0.647      -1.206       0.749
topic_36            -0.3467      0.430     -0.807      0.420      -1.189       0.495
topic_37             0.5316      0.285      1.868      0.062      -0.026       1.089
topic_38             0.0490      1.775      0.028      0.978      -3.431       3.529
topic_39            -1.1199      0.793     -1.413      0.158      -2.674       0.434
sentiment           -0.0233      0.082     -0.283      0.777      -0.184       0.138
uncertainty         -0.0776      0.067     -1.160      0.246      -0.209       0.054
==============================================================================
Omnibus:                       34.253   Durbin-Watson:                   1.930
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               33.340
Skew:                          -0.338   Prob(JB):                     5.76e-08
Kurtosis:                       2.684   Cond. No.                         214.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [76]:
def bootstrap_indirect_effect(df, x_cols, m_col, y_col, n_boot=500):
    inds = []
    for _ in range(n_boot):
        samp = df.sample(frac=1.0, replace=True)
        m = smf.ols(f"{m_col} ~ " + " + ".join(x_cols), data=samp).fit()
        y = smf.ols(f"{y_col} ~ {m_col} + " + " + ".join(x_cols), data=samp).fit()
        # aggregate indirect effect as mean over Xs: sum(a_i * b)
        b = y.params.get(m_col, 0)
        a = np.array([m.params.get(col, 0) for col in x_cols])
        inds.append((a * b).sum())
    return np.percentile(inds, [2.5, 50, 97.5])

ci = bootstrap_indirect_effect(df_m, structured + text_feats, risk_target, support_target)
print("\nBootstrap indirect effect CI (2.5%, 50%, 97.5%):", ci)

Bootstrap indirect effect CI (2.5%, 50%, 97.5%): [-6.14614707  0.57942611  4.7738177 ]

In [77]:
# 11. Research Question Checks
# Do language differences explain gender gaps?

In [78]:
# Compare gender coefficient with/without text features in Risk model
if "gender" in df_m.columns:
    base_cols = [c for c in structured if c != "gender"]
    m_base = smf.ols(f"{risk_target} ~ gender + " + " + ".join(base_cols), data=df_m).fit(cov_type='HC3')
    m_text = smf.ols(f"{risk_target} ~ gender + " + " + ".join(base_cols + text_feats), data=df_m).fit(cov_type='HC3')
    print("\nGender effect WITHOUT text features:", m_base.params.get("gender"))
    print("Gender effect WITH text features:", m_text.params.get("gender"))

In [79]:
df.to_csv("enhanced_with_topics_sentiment_uncertainty.csv", index=False)
feat_imp.to_csv("feature_importance_risk.csv", index=False)

print("\nPipeline complete.")

Pipeline complete.